
// This file has been generated by the GUI designer. Do not modify.
namespace CCalculadora
{
	public partial class Window2
	{
		private global::Gtk.Label label1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CCalculadora.Window2
			this.Name = "CCalculadora.Window2";
			this.Title = global::Mono.Unix.Catalog.GetString("Window2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CCalculadora.Window2.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("HOLA");
			this.Add(this.label1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
